# create service and bind azure load balancer
# https://kubernetes.io/docs/concepts/services-networking/service/
# https://docs.microsoft.com/en-us/azure/aks/static-ip
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
  selector:
    app: app1
    tier: fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8011
---
apiVersion: v1
kind: Service
metadata:
  name: app1-be-service
  namespace: app1
  annotations:
spec:
  selector:
    app: app1
    component: app1.be
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8011
---
apiVersion: v1
kind: Service
metadata:
  name: app1-be-vip-service
  namespace: app1
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
  selector:
    app: app1
    component: app1.be
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8011