FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
ARG VERSION
WORKDIR /build

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out -p:Version="$VERSION"

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /build
COPY --from=build-env /build/out .
ENTRYPOINT ["dotnet", "app1.runner.dll"]