# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app1
  labels:
    name: app1
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        tier: fe
    spec:
      containers:
      - name: app1-fe
        image: qliang.azurecr.io/app1.fe-image:107
        ports:
        - containerPort: 8011
---
# create service and bind azure load balancer
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: {VIP}
  selector:
    app: app1
    tier: fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8011