apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  labels:
    app: app1
    tier: fe
data:
  app1.fe.appsettings.json: |
    {
      "AppInfo": {
        "Title": "Today's Cats",
        "SiteName": "qliang-k8s-hosting",
        "ShowMachineInfo": true,
        "DelayStartInSec": 60
      }
    }
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        tier: fe
    spec:
      containers:
      - name: app1-fe
        image: qliang.azurecr.io/app1.fe-image:108
        ports:
        - containerPort: 8011
        volumeMounts:
        - name: appsettings
          mountPath: /app1.fe/k8sconfig
          readOnly: true
      volumes:
      - name: appsettings
        configMap:
          name: app1-config
---
# create service and bind azure load balancer
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: app1
    tier: fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8011