# Build App1 Image - CI

# Doc Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  version: '$(Build.BuildId)'
  registry: 'qliang-acr'
  component: '$(Component)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
          imageName: '$(component)-image'
    steps:
    - task: Docker@2
      displayName: login acr $(registry)
      inputs:
        containerRegistry: '$(registry)'
        command: 'login'
    - task: Docker@2
      displayName: Build image $(imageName)
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/$(component)/dockerfile'
        arguments: '--build-arg VERSION=$(version)'
        repository: $(imageName)
        tags: |
          $(version)
    - task: Docker@2
      displayName: Push image $(imageName)
      inputs:
        containerRegistry: '$(registry)'
        repository: '$(imageName)'
        command: 'push'
    - script: echo build succeed
      displayName: $(imageName):$(version) pushed