# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  registry: 'qliang-acr'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
          imageName: 'app1.fe-image'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app1.fe/dockerfile'
        repository: $(imageName)
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: '$(registry)'
        repository: '$(imageName)'
        command: 'push'