# Build App1 Image - CI

# Doc Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: build-push-image-template.yml
    parameters:
      version: $(Build.BuildId)
      registry: 'qliang-acr'
      component: 'app1-fe'
      imageName: 'app1-fe-image'
  - template: build-push-image-template.yml
    parameters:
      version: $(Build.BuildId)
      registry: 'qliang-acr'
      component: 'app1-be'
      imageName: 'app1-be-image'
  - template: build-push-image-template.yml
    parameters:
      version: $(Build.BuildId)
      registry: 'qliang-acr'
      component: 'app1-runner'
      imageName: 'app1-runner-image'