# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Deploy
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Kubernetes@1
    displayName: Deploy app1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: '$(kubeConnection)'
      command: 'apply'
      arguments: '-k $(Build.SourcesDirectory)/deployment/kustomize/environments/$(deployEnvironment)'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'