# Deploy App1 Preprod - CD 

jobs:
- job: Deploy
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Kubernetes@1
    displayName: Deploy app1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: '$(kubeConnection)'
      command: 'apply'
      arguments: '-k $(Build.SourcesDirectory)/deployment/kustomize/environments/$(deployEnvironment)'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'