FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
ARG VERSION
WORKDIR /app1.fe

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out -p:Version="$VERSION"

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app1.fe
COPY --from=build-env /app1.fe/out .
ENTRYPOINT ["dotnet", "app1.fe.dll", "--urls=http://0.0.0.0:8011"]