# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        tier: fe
    spec:
      containers:
      - name: app1-fe
        image: qliang.azurecr.io/app1.fe-image:v0.4
        ports:
        - containerPort: 8011
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
        - name: appsettings
          mountPath: /app1.fe/k8sconfig
          readOnly: true
      volumes:
      - name: azure
        csi:
          driver: file.csi.azure.com
          volumeAttributes:
            secretName: app1storage-secret
            shareName: qliangaksapp1share
      - name: appsettings
        configMap:
          name: app1-config