#service
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
spec:
  loadBalancerIP: 20.237.147.114
---
apiVersion: v1
kind: Service
metadata:
  name: app1-be-vip-service
  namespace: app1
spec:
  loadBalancerIP: 220.237.147.114