namespace: preprodapp1

bases:
  - ../../base

patches:
  - vip-patch.yaml

configMapGenerator:
- name: app1-config
  namespace: app1
  files:
    - app1.fe.appsettings.json
    - app1.runner.appsettings.json

images:
- name: qliang.azurecr.io/app1.fe-image
  newTag: '101'
- name: qliang.azurecr.io/app1.be-image
  newTag: '101'
- name: qliang.azurecr.io/app1.runner-image
  newTag: '103'